version: "3.4"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: voting
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
      MYSQL_DATABASE: voting
    ports:
      - "3306:3306"
    networks:
      - traefik-public
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: db
  redis:
    image: redis:alpine
    command: redis-server --requirepass voting
    depends_on:
      - mysql
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: dbredis
    networks:
      - traefik-public
  voting:
    image: registry.rebrainme.com/docker_users_repos/5229/dkr-30-voting/voting
    ports:
      - 9000:9000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: voting
      DB_USERNAME: voting
      DB_PASSWORD: voting
      REDIS_HOST: redis
      REDIS_PASSWORD: voting
    depends_on:
      - redis
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: app
    networks:
      - traefik-public
  nginx:
    image: nginx:1.17.2-alpine
    depends_on:
      - voting
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`voting.161.35.91.140.nip.io`) || (Host(`voting.167.172.45.109.nip.io`)) || (Host(`voting.165.232.90.119.nip.io`))"
        - "traefik.http.routers.nginx.entrypoints=web"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == manager 
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.:/var/www/html
    networks:
      - traefik-public

networks:
    traefik-public:
      driver: overlay
      external: true

volumes:
  db:
    driver: glusterfs
    name: "swarm-vols/db"
